/**
 * Centralized route paths — prevents magic strings throughout the app.
 */
export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",

  // Customer
  PRODUCTS: "/",
  PRODUCT_DETAIL: (slug: string) => `/${slug}`,
  CART: "/cart",
  CHECKOUT: "/checkout",
  ORDERS: "/orders",
  ORDER_LOOKUP: "/order-lookup",
  ACCOUNT: "/account",
  WISHLIST: "/wishlist",

  // Admin
  ADMIN: "/admin",
  ADMIN_DASHBOARD: "/admin",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_PRODUCTS_CREATE: "/admin/products/create",
  ADMIN_PRODUCTS_EDIT: (id: string) => `/admin/products/${id}`,
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_CATEGORIES_CREATE: "/admin/categories/create",
  ADMIN_BRANDS: "/admin/brands",
  ADMIN_BANNERS: "/admin/banners",
  ADMIN_BANNERS_CREATE: "/admin/banners/create",
  ADMIN_BANNERS_EDIT: (id: string) => `/admin/banners/${id}`,
  ADMIN_DISCOUNTS: "/admin/discounts",
  ADMIN_DISCOUNTS_CREATE: "/admin/discounts/create",
  ADMIN_DISCOUNTS_EDIT: (id: string) => `/admin/discounts/${id}`,
  ADMIN_ORDERS: "/admin/orders",
  ADMIN_ORDERS_CREATE: "/admin/orders/create",
  ADMIN_RETURNS: "/admin/returns",
  ADMIN_PAYMENTS: "/admin/payments",
  ADMIN_USERS: "/admin/users",
  ADMIN_USERS_CREATE: "/admin/users/create",
  ADMIN_REVIEWS: "/admin/reviews",
  ADMIN_CHAT: "/admin/chat",
  ADMIN_AI_CHATBOT: "/admin/ai-chatbot",
  ADMIN_REPORTS: "/admin/reports",
  ADMIN_NOTIFICATIONS: "/admin/notifications",
  ADMIN_LOGS: "/admin/logs",
  ADMIN_PERMISSIONS: "/admin/permissions",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_PROFILE: "/admin/profile",
} as const;
